#!/bin/bash

# Usage: jtool-pager [FILENAME]

########################################################################
# Bash environment
########################################################################

# Safety
set -o errexit  \
    -o pipefail \
    -o nounset  \
    -o noclobber

# Extensions
set +o posix
shopt -s lastpipe
shopt -s expand_aliases
shopt -s extglob
shopt -s globstar

########################################################################
# Handle private protocol
########################################################################

if (( $# == 1 )); then
    case $1 in
        -\?) exec less --help ;;
        -\:) exec cat <<SYNOPSYS
jtool CMD
   CMD sinopsys...
SYNOPSYS
            exit 0
            ;;
    esac
fi

########################################################################
# Command
########################################################################

# Arguments
declare FILENAME=${1:--} # `-` if not provided

# `jq` options
declare -a JQ_OPT=(
    --indent 4 
    --color-output
#   --compact-output    TODO: as parameter
)

# `less` options 
declare -a LESS_OPT=(
    --chop-long-lines
    --clear-screen
    --hilite-search
    --HILITE-UNREAD
    --ignore-case
    --LONG-PROMPT
    --no-init
    --quit-on-intr
    --RAW-CONTROL-CHARS
    --squeeze-blank-lines
    --status-column
)

# Paginate JSON!
jq ${JQ_OPT[@]} . "${FILENAME}" | less ${LESS_OPT[@]}

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
