#!/bin/bash

# Usage: jtool-journal [OPTIONS...] [MATCHES...]

# Safety
set -o errexit -o pipefail -o nounset -o noclobber

# Bash extensions
set +o posix
shopt -s lastpipe

# Options
declare -a JCTL_OPT=(
    --output=json
)

# Do it!
if [[ -t 1 ]]; then
    journalctl ${JCTL_OPT} "$@" | ${0%-*}-pager
else
    journalctl ${JCTL_OPT} "$@"
fi

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
