#!/bin/bash

# Usage: jtool-lshw [OPTIONS]

# Safety
set -o errexit -o pipefail -o nounset -o noclobber

# Bash extensions
set +o posix
shopt -s lastpipe

# Options
declare -a LSHW_OPT=(
    -json
)

# Do it!
lshw ${LSHW_OPT} "$@"

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
