#!/bin/bash

# Usage: jtool-lshw [OPTIONS]

# Safety
set -o errexit -o pipefail -o nounset -o noclobber

# Bash extensions
set +o posix
shopt -s lastpipe

# Options
declare -a LSHW_OPT=(
    -json
)

# Do it!
if [[ -t 1 ]]; then
    lshw ${LSHW_OPT} "$@" | ${0%-*}-pager
else
    lshw ${LSHW_OPT} "$@"
fi

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
