#!/bin/bash

# Usage: jtool-journal [OPTIONS] [MATCHES]

########################################################################
# Bash environment
########################################################################

# Safety
set -o errexit  \
    -o pipefail \
    -o nounset  \
    -o noclobber

# Extensions
set +o posix
shopt -s lastpipe
shopt -s expand_aliases
shopt -s extglob
shopt -s globstar
shopt -s nullglob

########################################################################
# Handle private protocol
########################################################################

if (( $# > 0 )); then
    case $1 in
        -\?)
            journalctl --help
            exit
            ;;
        -\:)
            cat <<SYNOPSYS
jtool CMD
   CMD sinopsys...
SYNOPSYS
            exit 0
            ;;
    esac
fi

########################################################################
# Command
########################################################################

# `journalctl` options
declare -a JCTL_OPT=(
    --output=json
)

# `journalctl` with JSON output!
exec journalctl ${JCTL_OPT} "$@"

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
