#!/bin/bash

# Usage: jtool-ls [OPTIONS] FILE...

########################################################################
# Bash environment
########################################################################

# Safety
set -o errexit  \
    -o pipefail \
    -o nounset  \
    -o noclobber

# Extensions
set +o posix
shopt -s lastpipe
shopt -s expand_aliases
shopt -s extglob
shopt -s globstar
shopt -s nullglob

########################################################################
# Handle private protocol
########################################################################

if (( $# == 1 )); then
    case $1 in
        -\?)
            if [[ -t 1 ]]; then
                ls --help | less
            else
                ls --help
            fi
            exit
            ;;
        -\:)
            cat <<SYNOPSYS
jtool CMD
   CMD sinopsys...
SYNOPSYS
            exit 0
            ;;
    esac
fi

########################################################################
# Command
########################################################################

# `ls` options
declare -a LS_OPT=(
    -l
    --time-style=full-iso
)

# `jq` options
declare -a JQ_OPT=(
    --slurp
    --raw-input
    --indent 4 
)

# `ls` with JSON output!
ls ${LS_OPT[@]} "$@"        \
| sed   -e '1d'             \
        -e 's/[ \t]\+/ /g'  \
| jq ${JQ_OPT[@]}           \
'   (./"\n") as $lines
    | $lines[0:-1][]
    | (./" ") as $fields
    | {
        "mode": $fields[0],
        "nlinks": $fields[1],
        "user": $fields[2],
        "group": $fields[3],
        "size": $fields[4],
        "date": $fields[5],
        "time": $fields[6],
        "TZ": $fields[7],
        "name": $fields[8]
      }
'

########################################################################
# Bugs:
#   Do not manage spaces in file names.
########################################################################

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
