#!/bin/bash

# Usage: jtool [OPTIONS] COMMAND

########################################################################
# Bash environment
########################################################################

# Safety
set -o errexit  \
    -o pipefail \
    -o nounset  \
    -o noclobber

# Extensions
set +o posix
shopt -s lastpipe
shopt -s expand_aliases
shopt -s extglob
shopt -s globstar

########################################################################
# Global declarations
########################################################################

# `jq` options
declare -a JQ_OPT=(
    --indent 4 
    --color-output
#   --compact-output    TODO: as parameter
)

# `less` options 
declare -a LESS_OPT=(
    --chop-long-lines
    --clear-screen
    --hilite-search
    --HILITE-UNREAD
    --ignore-case
    --LONG-PROMPT
    --no-init
    --quit-on-intr
    --RAW-CONTROL-CHARS
    --squeeze-blank-lines
    --status-column
)

alias print='echo 1>&2 -e'
alias message='cat 1>&2'

function fatal
{
    print "fatal: $@"
    exit 1
}

########################################################################
# Builtin commands
########################################################################

function helper
{
    local tool=$1

    $tool -\? | less ${LESS_OPT[@]}
}

function formatter
{
    local filename=$1

    jq ${JQ_OPT[@]} . "${filename}" 
}

function pager
{
    # Arguments
    local filename=$1

    # Paginate JSON!
    formatter "${filename}" | less ${LESS_OPT[@]}
}

########################################################################
# Command
########################################################################

# Get command
declare COMMAND=${1?Expected command}
shift

case ${COMMAND} in
    help)
        (( $# == 1 )) || fatal 'Expected command name'
        declare about=$1
        case ${about} in
            help)   # help about help
                echo TODO ;;
            pager)  # help about pager
                exec less --help ;;
            *)      # help about $about
                declare TOOL=$0-${about}
                helper ${TOOL} ;;
        esac
        ;;
    pager)
        pager ${1:--}
        ;;
    *)
        declare TOOL=$0-${COMMAND}
        if [[ -t 1 ]]; then
            ${TOOL} "$@" | pager -
        else
            ${TOOL} "$@"
        fi
esac

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
