#!/bin/bash

# Usage: jtool-ls [OPTIONS] FILE...

########################################################################
# Bash environment
########################################################################

# Safety
set -o errexit  \
    -o pipefail \
    -o nounset  \
    -o noclobber

# Extensions
set +o posix
shopt -s lastpipe
shopt -s expand_aliases
shopt -s extglob
shopt -s globstar

########################################################################
# Handle private protocol
########################################################################

if (( $# == 1 )); then
    case $1 in
        -\?) exec ls --help ;;
        -\:) exec cat <<SYNOPSYS
jtool CMD
   CMD sinopsys...
SYNOPSYS
            exit 0
            ;;
    esac
fi

########################################################################
# JQ script
########################################################################

JQ_SCRIPT='/dev/fd/7'   # to close: exec 7<&-

exec 7<<\JQEOF
# input is lps` output as a big string with spaces trimmed
(./"\n") as $lines
| $lines[0:-1][]
| (./" ") as $fields
| {
    "mode": $fields[0],
    "nlinks": $fields[1],
    "user": $fields[2],
    "group": $fields[3],
    "size": $fields[4],
    "date": $fields[5],
    "time": $fields[6],
    "TZ": $fields[7],
    "name": $fields[8]
  }
JQEOF

########################################################################
# Command
########################################################################

# `ls` options
declare -a LS_OPT=(
    -l
    --time-style=full-iso
)

# `jq` options
declare -a JQ_OPT=(
    --slurp
    --raw-input
    --indent 4 
    --from-file ${JQ_SCRIPT}
)

# Filter to delete 1st line and trim spaces
declare -a SED_FILTER=(
    -e '1d'
    -e 's/[ \t]\+/ /g'
)

# `ls` with JSON output!
  ls ${LS_OPT[@]} "$@"      \
| sed "${SED_FILTER[@]}"    \
| jq "${JQ_OPT[@]}"

########################################################################
# Bugs:
#   Do not manage spaces in file names.
########################################################################

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
