#!/bin/bash

# Usage: jtool-pager [FILENAME]

# Safety
set -o errexit -o pipefail -o nounset -o noclobber

# Bash extensions
set +o posix
shopt -s lastpipe

# Arguments
declare FILENAME=${1:--}

# Options
declare -a JQ_OPT=(
    --indent 4 
    --color-output
)

declare -a LESS_OPT=(
    --chop-long-lines
    --clear-screen
    --hilite-search
    --HILITE-UNREAD
    --ignore-case
    --LONG-PROMPT
    --RAW-CONTROL-CHARS
    --squeeze-blank-lines
    --status-column
)

# Do it!
jq ${JQ_OPT[@]} . "${FILENAME}" | less ${LESS_OPT[@]}

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
