#!/bin/bash

# Usage: jtool-journal [OPTIONS...] [MATCHES...]

JCTL_OPT=(
    --output=json
)

# Do it!
if [[ -t 1 ]]; then
    journalctl ${JCTL_OPT} "$@" | ${0%-*}-pager
else
    journalctl ${JCTL_OPT} "$@"
fi

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
