#!/bin/bash

# Usage: jtool-lshw [OPTIONS]

########################################################################
# Bash environment
########################################################################

# Safety
set -o errexit  \
    -o pipefail \
    -o nounset  \
    -o noclobber

# Extensions
set +o posix
shopt -s lastpipe
shopt -s expand_aliases
shopt -s extglob
shopt -s globstar
shopt -s nullglob

########################################################################
# Command
########################################################################

# `lshw` options
declare -a LSHW_OPT=(
    -json
)

# `lshw` with JSON output!
exec lshw ${LSHW_OPT} "$@"

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
