#!/bin/bash

# Usage: jtool-stat [OPTIONS] FILE...

########################################################################
# Bash environment
########################################################################

# Safety
set -o errexit  \
    -o pipefail \
    -o nounset  \
    -o noclobber

# Extensions
set +o posix
shopt -s lastpipe
shopt -s expand_aliases
shopt -s extglob
shopt -s globstar
shopt -s nullglob

########################################################################
# Handle private protocol
########################################################################

if (( $# > 0 )); then
    case $1 in
        -\?)
            stat --help | less
            exit
            ;;
        -\:)
            cat <<SYNOPSYS
jtool CMD
   CMD sinopsys...
SYNOPSYS
            exit 0
            ;;
    esac
fi

########################################################################
# Command
########################################################################

# `stat` with JSON output!
exec stat --printf '{
    "mode": "%A",
    "nlink": %h,
    "uid": "%u",
    "user": "%U",
    "gid": "%g",
    "group": "%G",
    "size": %s,
    "mtime": "%y",
    "name": "%n"
}'"\n" "$@"

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
