#!/bin/bash

# Usage: jtool [OPTIONS] COMMAND

########################################################################
# Bash environment
########################################################################

# Safety
set -o errexit  \
    -o pipefail \
    -o nounset  \
    -o noclobber

# Extensions
set +o posix
shopt -s lastpipe
shopt -s expand_aliases
shopt -s extglob
shopt -s globstar
shopt -s nullglob

########################################################################
# Parse `jtool` options
########################################################################

# getopts...

########################################################################
# Command
########################################################################

# Get command
declare COMMAND=${1?Expected command}
declare TOOL=$0-${COMMAND}
shift

# TODO: check all!!!
if [[ ${COMMAND} == help ]]; then
    # $1 is defined or die...
    $0-$1 -\?
# Call command!
elif [[ -t 1 && ${TOOL} != *-pager ]]; then
    ${TOOL} "$@" | ${0}-pager
else
    ${TOOL} "$@"
fi

exit

# vim:syntax=sh:et:sw=4:ts=4:ai
